### ISSUE TITLE
Если код != 200, то возврат не произойдет?

### ISSUE THREAD

**Issue by Alsaril** [Mitronins/measurements#12]
https://github.com/Mitronins/measurements/blob/4aa110d4285e24417df746e37480a714650f1eb6/src/main/java/com/addd/measurements/activity/OneMeasurementActivity.kt#L153

**Comment by Alsaril** [comment]
https://github.com/Mitronins/measurements/blob/4aa110d4285e24417df746e37480a714650f1eb6/src/main/java/com/addd/measurements/activity/TransferActivity.kt#L103

**Comment by smitronin** [comment]
ну да, тут меня волнует, если что-то изменилось, то придет 200 - и я обновлю список замеров. Если любой другой - ничего делать не надо.
