### ISSUE TITLE
Вынести в главный конструктор

### ISSUE THREAD

**Issue by Alsaril** [Mitronins/measurements#18]
https://github.com/Mitronins/measurements/blob/4aa110d4285e24417df746e37480a714650f1eb6/src/main/java/com/addd/measurements/adapters/ClientAdapter.kt#L23

**Comment by Alsaril** [comment]
https://github.com/Mitronins/measurements/blob/4aa110d4285e24417df746e37480a714650f1eb6/src/main/java/com/addd/measurements/adapters/ClientAdapter.kt#L96

Тоже. Присвоение переменной можно сделать в `init`

**Comment by Alsaril** [comment]
https://github.com/Mitronins/measurements/blob/4aa110d4285e24417df746e37480a714650f1eb6/src/main/java/com/addd/measurements/modelAPI/Authorization.kt#L9

**Comment by Alsaril** [comment]
И во всех моделях перенсти поля в главный конструктор и избавиться от ?

**Comment by smitronin** [comment]
от ? не могу избавиться, так как null может же прийти из запроса
