### ISSUE TITLE
Лучше перенести этот код в родителя RecyclerView и назначить его обработчиком

### ISSUE THREAD

**Issue by Alsaril** [Mitronins/measurements#20]
https://github.com/Mitronins/measurements/blob/4aa110d4285e24417df746e37480a714650f1eb6/src/main/java/com/addd/measurements/adapters/ClientAdapter.kt#L63-L80

**Comment by smitronin** [comment]
проблема в том, что если так сделаю, то как узнать id элемента на который нажали?

**Comment by Alsaril** [comment]
onClick на вход получает View, на котором кликнули. У него можно получить id

**Comment by smitronin** [comment]
смотри, я нажму, получу вьюху, в ней есть номер сделки и всякая фигня, но id самого замера - нет. id я узнавал только из адаптера, из массива замеров

**Comment by Alsaril** [comment]
list.getChildLayoutPosition(v) -- индекс элемента

**Comment by smitronin** [comment]
получается, тогда во фрагменте есть массив, который я собственно передаю адаптеру. И если определить листенер во фрагменте, мне надо будет просто брать list.getChildLayoutPosition(v) и по этой позиции взять из массива замер?

**Comment by Alsaril** [comment]
Адаптер содержит все данные. Так что можно из него узнать. Необязательно список во фрагменте хранить

**Comment by smitronin** [comment]
не совсем понимаю как из класса фрагмента я получу доступ к списку в классе адаптера?

**Comment by Alsaril** [comment]
Сделай поле list публичным

**Comment by Alsaril** [comment]
ну или метод getList

**Comment by Alsaril** [comment]
https://github.com/Alsaril/rest-client/blob/30b8d8bd195b531724b0df34afd7011c013c407d/app/src/main/java/com/natcom/activity/ListActivity.kt#L206

https://github.com/Alsaril/rest-client/blob/30b8d8bd195b531724b0df34afd7011c013c407d/app/src/main/java/com/natcom/activity/ListActivity.kt#L245

У меня лист был константным

**Comment by Alsaril** [comment]
Можно как вариант сделать метод, который по индексу возвращает элемент. Тогда лист наружу не вылезет
