### ISSUE TITLE
Адаптер не может отвечать за взаимодействие с сетью

### ISSUE THREAD

**Issue by Alsaril** [Mitronins/measurements#21]
https://github.com/Mitronins/measurements/blob/4aa110d4285e24417df746e37480a714650f1eb6/src/main/java/com/addd/measurements/adapters/DataAdapter.kt#L29

**Comment by Alsaril** [comment]
Вся логика должна быть во фрагменте или активити. Адаптер только отображает данные

**Comment by smitronin** [comment]
тут только для того, чтобы листенер повесить, вот если смогу их(листенеры) перенести во фрагмент, то и нетворкконтроллера не будет здесь

**Comment by Alsaril** [comment]
Переноси
